
default_platform(:android)

platform :android do
  desc "Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
   firebase_app_distribution(
    app: "1:950383329589:android:455e9fc3fc87698cc34c7c",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type:"APK",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers:"melbaz187@gmail.com",
    release_notes:"Test Release Firebase App Distribution v.1.0.4" 
  )
  end
end
